### ISSUE TITLE
Move the guide from the wiki to the GitHub repo

### ISSUE THREAD

**Issue by hkdobrev** [nstevens/androidguide#1]
If you move the guide to the GitHub repo instead of the wiki, you would be able to accept pull requests.

For reference: https://github.com/interagent/http-api-design/

---

Keeping guidelines and documentation in the GitHub wiki makes sense when you have another project in the GitHub repo and the wiki is for the project. Then you normally don't want/expect pull requests for the guidelines/documentation, but rather for the source code of the project itself.

In this scenario the wiki is the project itself, so it's better to move it to files and folders of Markdown files in the repo. The editing interface is not that different than the wiki, but I admit it is more technical. But this is not targeted for non-technical people.

**Comment by nstevens** [comment]
Thanks for the tip @hkdobrev! Updated in https://github.com/nstevens/androidguide/pull/2
